# Control buttons: boost timer, fan level, manual mode, passive temperature
# and humidity comfort.
substitutions:
  entity_prefix: "comfoair "

button:
  - platform: zehnder_comfoair_q
    boost_15min: {id: boost_15min, name: "${entity_prefix}Boost 15 Min."}
    boost_30min: {id: boost_30min, name: "${entity_prefix}Boost 30 Min."}
    boost_off: {id: boost_off, name: "${entity_prefix}Boost off"}
    fan_level_0: {id: fan_level_0, name: "${entity_prefix}Set level 0"}
    fan_level_1: {id: fan_level_1, name: "${entity_prefix}Set level 1"}
    fan_level_2: {id: fan_level_2, name: "${entity_prefix}Set level 2"}
    fan_level_3: {id: fan_level_3, name: "${entity_prefix}Set level 3"}
    manual_mode_on: {id: manual_mode_on, name: "${entity_prefix}Set manual mode on"}
    manual_mode_off: {id: manual_mode_off, name: "${entity_prefix}Set manual mode off"}
    passive_temperature_auto: {id: passive_temperature_auto, name: "${entity_prefix}Set passive temperature auto"}
    passive_temperature_off: {id: passive_temperature_off, name: "${entity_prefix}Set passive temperature off"}
    humidity_comfort_auto: {id: humidity_comfort_auto, name: "${entity_prefix}Set humidity comfort auto"}
    humidity_comfort_off: {id: humidity_comfort_off, name: "${entity_prefix}Set humidity comfort off"}
